use serde::{Deserialize, Serialize};
use serde_json::Value;
use surrealdb::types::{Datetime, RecordId, SurrealValue};

#[derive(Debug, Clone, Deserialize, SurrealValue)]
pub struct Room {
    pub id: Option<RecordId>,
    pub game_id: String,
    pub host_id: RecordId,
    pub name: String,
    pub max_players: u32,
    pub status: RoomStatus,
    #[serde(default)]
    pub players: Vec<RecordId>,
    pub human_timeout_ms: Option<u32>,
    /// Set when the room is generated by tournament matchmaking. Carries
    /// the participant pairing forward so finishing the room writes back
    /// to the right `match` row.
    #[serde(default)]
    pub tournament_id: Option<RecordId>,
    /// Ranked rooms (auto-created by tournament matchmaker) restrict
    /// joins to these user IDs. Unranked rooms leave it empty.
    #[serde(default)]
    pub allowed_user_ids: Vec<RecordId>,
    #[serde(default)]
    pub is_ranked: bool,
    #[serde(default)]
    pub winner_id: Option<RecordId>,
    #[serde(default)]
    pub event_history: Vec<String>,
    /// Open per-game configuration blob. Each game's logic owns the
    /// shape: ttt uses `{board_size, win_chain}`; rps/pd `{rounds}`;
    /// chess/xiangqi `{time_pool_minutes, time_per_turn_seconds, blind}`.
    /// The api never validates the shape — the judge logic does.
    #[serde(default = "default_config")]
    pub config: Value,
    pub created_at: Datetime,
    pub updated_at: Datetime,
}

fn default_config() -> Value {
    Value::Object(serde_json::Map::new())
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, SurrealValue)]
#[serde(rename_all = "lowercase")]
#[surreal(untagged, lowercase)]
pub enum RoomStatus {
    Lobby,
    Playing,
    Finished,
    Abandoned,
}
